# Model 2 data preparation

In [1]:
import pandas as pd

In [2]:
df_train = pd.read_csv('/Users/drkazimieras/Turing College/Home credit default risk/data files/application_train.csv')
df_bureau = pd.read_csv('/Users/drkazimieras/Turing College/Home credit default risk/data files/bureau.csv')
df_credit_card = pd.read_csv('/Users/drkazimieras/Turing College/Home credit default risk/data files/credit_card_balance.csv')

In [3]:
df = pd.merge(df_train, df_bureau, on='SK_ID_CURR', how='inner')
df = pd.merge(df, df_credit_card, on='SK_ID_CURR', how='inner')

In [4]:
pd.set_option("display.max_column", None)
df.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY_x,AMT_GOODS_PRICE,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_EMPLOYED,DAYS_REGISTRATION,DAYS_ID_PUBLISH,OWN_CAR_AGE,FLAG_MOBIL,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,LIVE_REGION_NOT_WORK_REGION,REG_CITY_NOT_LIVE_CITY,REG_CITY_NOT_WORK_CITY,LIVE_CITY_NOT_WORK_CITY,ORGANIZATION_TYPE,EXT_SOURCE_1,EXT_SOURCE_2,EXT_SOURCE_3,APARTMENTS_AVG,BASEMENTAREA_AVG,YEARS_BEGINEXPLUATATION_AVG,YEARS_BUILD_AVG,COMMONAREA_AVG,ELEVATORS_AVG,ENTRANCES_AVG,FLOORSMAX_AVG,FLOORSMIN_AVG,LANDAREA_AVG,LIVINGAPARTMENTS_AVG,LIVINGAREA_AVG,NONLIVINGAPARTMENTS_AVG,NONLIVINGAREA_AVG,APARTMENTS_MODE,BASEMENTAREA_MODE,YEARS_BEGINEXPLUATATION_MODE,YEARS_BUILD_MODE,COMMONAREA_MODE,ELEVATORS_MODE,ENTRANCES_MODE,FLOORSMAX_MODE,FLOORSMIN_MODE,LANDAREA_MODE,LIVINGAPARTMENTS_MODE,LIVINGAREA_MODE,NONLIVINGAPARTMENTS_MODE,NONLIVINGAREA_MODE,APARTMENTS_MEDI,BASEMENTAREA_MEDI,YEARS_BEGINEXPLUATATION_MEDI,YEARS_BUILD_MEDI,COMMONAREA_MEDI,ELEVATORS_MEDI,ENTRANCES_MEDI,FLOORSMAX_MEDI,FLOORSMIN_MEDI,LANDAREA_MEDI,LIVINGAPARTMENTS_MEDI,LIVINGAREA_MEDI,NONLIVINGAPARTMENTS_MEDI,NONLIVINGAREA_MEDI,FONDKAPREMONT_MODE,HOUSETYPE_MODE,TOTALAREA_MODE,WALLSMATERIAL_MODE,EMERGENCYSTATE_MODE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE,DAYS_LAST_PHONE_CHANGE,FLAG_DOCUMENT_2,FLAG_DOCUMENT_3,FLAG_DOCUMENT_4,FLAG_DOCUMENT_5,FLAG_DOCUMENT_6,FLAG_DOCUMENT_7,FLAG_DOCUMENT_8,FLAG_DOCUMENT_9,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_12,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY_y,SK_ID_PREV,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,100011,0,Cash loans,F,N,Y,0,112500.0,1019610.0,33826.5,913500.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.018634,-20099,365243,-7427.0,-3514,NaN,1,0,0,1,0,0,NaN,2.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,XNA,0.587334,0.205747,0.751724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,5741082,Closed,currency 1,-2508,0,-2173.0,-2197.0,10147.23,0,90744.3,0.0,0.0,0.0,Consumer credit,-2172,NaN,1843384,-48,75109.95,180000,0.0,0.0,0.0,0.0,9000.0,9000.000,9000.0,71127.360,75109.95,75109.95,0.0,0,0.0,0.0,27.0,Active,0,0
1,100011,0,Cash loans,F,N,Y,0,112500.0,1019610.0,33826.5,913500.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.018634,-20099,365243,-7427.0,-3514,NaN,1,0,0,1,0,0,NaN,2.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,XNA,0.587334,0.205747,0.751724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,5741082,Closed,currency 1,-2508,0,-2173.0,-2197.0,10147.23,0,90744.3,0.0,0.0,0.0,Consumer credit,-2172,NaN,1843384,-4,0.00,90000,0.0,0.0,0.0,0.0,0.0,563.355,0.0,0.000,0.00,0.00,0.0,0,0.0,0.0,33.0,Active,0,0
2,100011,0,Cash loans,F,N,Y,0,112500.0,1019610.0,33826.5,913500.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.018634,-20099,365243,-7427.0,-3514,NaN,1,0,0,1,0,0,NaN,2.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,XNA,0.587334,0.205747,0.751724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,5741082,Closed,currency 1,-2508,0,-2173.0,-2197.0,10147.23,0,90744.3,0.0,0.0,0.0,Consumer credit,-2172,NaN,1843384,-6,0.00,90000,0.0,0.0,0.0,0.0,0.0,563.355,0.0,0.000,0.00,0.00,0.0,0,0.0,0.0,33.0,Active,0,0
3,100011,0,Cash loans,F,N,Y,0,112500.0,1019610.0,33826.5,913500.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.018634,-20099,365243,-7427.0,-3514,NaN,1,0,0,1,0,0,NaN,2.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,XNA,0.587334,0.205747,0.751724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,5741082,Closed,currency 1,-2508,0,-2173.0,-2197.0,10147.23,0,90744.3,0.0,0.0,0.0,Consumer credit,-2172,NaN,1843384,-54,104130.63,180000,0.0,0.0,0.0,0.0,9000.0,9000.000,9000.0,99744.615,104130.63,104130.63,0.0,0,0.0,0.0,21.0,Active,0,0
4,100011,0,Cash loans,F,N,Y,0,112500.0,1019610.0,33826.5,913500.0,Children,Pensioner,Secondary / secondary special,Married,House / apartment,0.018634,-20099,365243,-7427.0,-3514,NaN,1,0,0,1,0,0,NaN,2.0,2,2,WEDNESDAY,14,0,0,0,0,0,0,XNA,0.587334,0.205747,0.751724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,1.0,0.0,0.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0,5741082,Closed,currency 1,-2508,0,-2173.0,-2197.0,10147.23,0,90744.3,0.0,0.0,0.0,Consumer credit,-2172,NaN,1843384,-18,0.00,180000,0.0,0.0,0.0,0.0,0.0,563.355,0.0,0.000,0.00,0.00,0.0,0,0.0,0.0,33.0,Active,0,0

In [5]:
df_feature_names = df.columns

# "list" as a work around for truncation
print(list(df_feature_names))

['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL', 'AMT_CREDIT', 'AMT_ANNUITY_x', 'AMT_GOODS_PRICE', 'NAME_TYPE_SUITE', 'NAME_INCOME_TYPE', 'NAME_EDUCATION_TYPE', 'NAME_FAMILY_STATUS', 'NAME_HOUSING_TYPE', 'REGION_POPULATION_RELATIVE', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'DAYS_REGISTRATION', 'DAYS_ID_PUBLISH', 'OWN_CAR_AGE', 'FLAG_MOBIL', 'FLAG_EMP_PHONE', 'FLAG_WORK_PHONE', 'FLAG_CONT_MOBILE', 'FLAG_PHONE', 'FLAG_EMAIL', 'OCCUPATION_TYPE', 'CNT_FAM_MEMBERS', 'REGION_RATING_CLIENT', 'REGION_RATING_CLIENT_W_CITY', 'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START', 'REG_REGION_NOT_LIVE_REGION', 'REG_REGION_NOT_WORK_REGION', 'LIVE_REGION_NOT_WORK_REGION', 'REG_CITY_NOT_LIVE_CITY', 'REG_CITY_NOT_WORK_CITY', 'LIVE_CITY_NOT_WORK_CITY', 'ORGANIZATION_TYPE', 'EXT_SOURCE_1', 'EXT_SOURCE_2', 'EXT_SOURCE_3', 'APARTMENTS_AVG', 'BASEMENTAREA_AVG', 'YEARS_BEGINEXPLUATATION_AVG', 'YEARS_BUILD_AVG', 'COMMONAREA_AVG', 'ELEVATORS_AVG', 'ENTRANCES_AVG', 'FLOORSMAX_AVG', 'FLOORSMIN_AVG', 'LANDAREA_AVG', 'LIVINGAPARTMENTS_AVG', 'LIVINGAREA_AVG', 'NONLIVINGAPARTMENTS_AVG', 'NONLIVINGAREA_AVG', 'APARTMENTS_MODE', 'BASEMENTAREA_MODE', 'YEARS_BEGINEXPLUATATION_MODE', 'YEARS_BUILD_MODE', 'COMMONAREA_MODE', 'ELEVATORS_MODE', 'ENTRANCES_MODE', 'FLOORSMAX_MODE', 'FLOORSMIN_MODE', 'LANDAREA_MODE', 'LIVINGAPARTMENTS_MODE', 'LIVINGAREA_MODE', 'NONLIVINGAPARTMENTS_MODE', 'NONLIVINGAREA_MODE', 'APARTMENTS_MEDI', 'BASEMENTAREA_MEDI', 'YEARS_BEGINEXPLUATATION_MEDI', 'YEARS_BUILD_MEDI', 'COMMONAREA_MEDI', 'ELEVATORS_MEDI', 'ENTRANCES_MEDI', 'FLOORSMAX_MEDI', 'FLOORSMIN_MEDI', 'LANDAREA_MEDI', 'LIVINGAPARTMENTS_MEDI', 'LIVINGAREA_MEDI', 'NONLIVINGAPARTMENTS_MEDI', 'NONLIVINGAREA_MEDI', 'FONDKAPREMONT_MODE', 'HOUSETYPE_MODE', 'TOTALAREA_MODE', 'WALLSMATERIAL_MODE', 'EMERGENCYSTATE_MODE', 'OBS_30_CNT_SOCIAL_CIRCLE', 'DEF_30_CNT_SOCIAL_CIRCLE', 'OBS_60_CNT_SOCIAL_CIRCLE', 'DEF_60_CNT_SOCIAL_CIRCLE', 'DAYS_LAST_PHONE_CHANGE', 'FLAG_DOCUMENT_2', 'FLAG_DOCUMENT_3', 'FLAG_DOCUMENT_4', 'FLAG_DOCUMENT_5', 'FLAG_DOCUMENT_6', 'FLAG_DOCUMENT_7', 'FLAG_DOCUMENT_8', 'FLAG_DOCUMENT_9', 'FLAG_DOCUMENT_10', 'FLAG_DOCUMENT_11', 'FLAG_DOCUMENT_12', 'FLAG_DOCUMENT_13', 'FLAG_DOCUMENT_14', 'FLAG_DOCUMENT_15', 'FLAG_DOCUMENT_16', 'FLAG_DOCUMENT_17', 'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20', 'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR', 'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK', 'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT', 'AMT_REQ_CREDIT_BUREAU_YEAR', 'SK_ID_BUREAU', 'CREDIT_ACTIVE', 'CREDIT_CURRENCY', 'DAYS_CREDIT', 'CREDIT_DAY_OVERDUE', 'DAYS_CREDIT_ENDDATE', 'DAYS_ENDDATE_FACT', 'AMT_CREDIT_MAX_OVERDUE', 'CNT_CREDIT_PROLONG', 'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_LIMIT', 'AMT_CREDIT_SUM_OVERDUE', 'CREDIT_TYPE', 'DAYS_CREDIT_UPDATE', 'AMT_ANNUITY_y', 'SK_ID_PREV', 'MONTHS_BALANCE', 'AMT_BALANCE', 'AMT_CREDIT_LIMIT_ACTUAL', 'AMT_DRAWINGS_ATM_CURRENT', 'AMT_DRAWINGS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT', 'AMT_DRAWINGS_POS_CURRENT', 'AMT_INST_MIN_REGULARITY', 'AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT', 'AMT_RECEIVABLE_PRINCIPAL', 'AMT_RECIVABLE', 'AMT_TOTAL_RECEIVABLE', 'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_CURRENT', 'CNT_DRAWINGS_OTHER_CURRENT', 'CNT_DRAWINGS_POS_CURRENT', 'CNT_INSTALMENT_MATURE_CUM', 'NAME_CONTRACT_STATUS', 'SK_DPD', 'SK_DPD_DEF']

In [6]:
df.shape

(18655456, 160)

Now there seems to be over 18 million data entries. However, wast majority of information comes from train_df, that only has around 300 000 data entries (clients' info). This means that one client from df_train corresponds to multiple entries in other tables. This much data is inpractical to work considering performance available, thus it will be reduced.

In [7]:
df_reduced, _ = train_test_split(df, test_size=0.7, stratify=df['TARGET'], random_state=42)

In [8]:
df_reduced.shape

(5596636, 160)

In [9]:
pd.set_option("display.max_rows", None)

df = df_reduced

num_of_rows = len(df)
missing_values = df.isnull().sum()
missing_percentage = (missing_values / num_of_rows) * 100

missing_percentage_df = pd.DataFrame(
    {
        "Missing values (count)": missing_values,
        "Missing values (%)": missing_percentage,
    }
).sort_values("Missing values (%)", ascending=False)

missing_percentage_df = missing_percentage_df[
    missing_percentage_df["Missing values (%)"] > 0
]

missing_percentage_df

                              Missing values (count)  Missing values (%)
AMT_ANNUITY_y                                4194557           74.947826
AMT_CREDIT_MAX_OVERDUE                       3689959           65.931731
COMMONAREA_MEDI                              3685186           65.846448
COMMONAREA_MODE                              3685186           65.846448
COMMONAREA_AVG                               3685186           65.846448
NONLIVINGAPARTMENTS_MEDI                     3666956           65.520716
NONLIVINGAPARTMENTS_MODE                     3666956           65.520716
NONLIVINGAPARTMENTS_AVG                      3666956           65.520716
FONDKAPREMONT_MODE                           3604305           64.401276
LIVINGAPARTMENTS_AVG                         3596465           64.261192
LIVINGAPARTMENTS_MEDI                        3596465           64.261192
LIVINGAPARTMENTS_MODE                        3596465           64.261192
FLOORSMIN_MODE                               3571694           63.818587
FLOORSMIN_AVG                                3571694           63.818587
FLOORSMIN_MEDI                               3571694           63.818587
OWN_CAR_AGE                                  3550823           63.445666
YEARS_BUILD_AVG                              3482371           62.222574
YEARS_BUILD_MODE                             3482371           62.222574
YEARS_BUILD_MEDI                             3482371           62.222574
LANDAREA_AVG                                 3052813           54.547285
LANDAREA_MEDI                                3052813           54.547285
LANDAREA_MODE                                3052813           54.547285
BASEMENTAREA_MEDI                            2991112           53.444819
BASEMENTAREA_MODE                            2991112           53.444819
BASEMENTAREA_AVG                             2991112           53.444819
EXT_SOURCE_1                                 2878282           51.428787
NONLIVINGAREA_AVG                            2780386           49.679593
NONLIVINGAREA_MODE                           2780386           49.679593
NONLIVINGAREA_MEDI                           2780386           49.679593
ELEVATORS_MEDI                               2676049           47.815313
ELEVATORS_AVG                                2676049           47.815313
ELEVATORS_MODE                               2676049           47.815313
APARTMENTS_MEDI                              2546956           45.508695
APARTMENTS_AVG                               2546956           45.508695
APARTMENTS_MODE                              2546956           45.508695
WALLSMATERIAL_MODE                           2537847           45.345936
HOUSETYPE_MODE                               2513244           44.906333
ENTRANCES_MODE                               2511237           44.870472
ENTRANCES_MEDI                               2511237           44.870472
ENTRANCES_AVG                                2511237           44.870472
LIVINGAREA_MODE                              2506142           44.779435
LIVINGAREA_MEDI                              2506142           44.779435
LIVINGAREA_AVG                               2506142           44.779435
FLOORSMAX_AVG                                2481274           44.335097
FLOORSMAX_MEDI                               2481274           44.335097
FLOORSMAX_MODE                               2481274           44.335097
YEARS_BEGINEXPLUATATION_MODE                 2426666           43.359368
YEARS_BEGINEXPLUATATION_MEDI                 2426666           43.359368
YEARS_BEGINEXPLUATATION_AVG                  2426666           43.359368
TOTALAREA_MODE                               2399736           42.878186
EMERGENCYSTATE_MODE                          2350212           41.993297
DAYS_ENDDATE_FACT                            2076044           37.094497
AMT_CREDIT_SUM_LIMIT                         1942335           34.705402
OCCUPATION_TYPE                              1635039           29.214675
AMT_PAYMENT_CURRENT                          1000953           17.884904
AMT_DRAWINGS_ATM_CURRENT                      986559           17.627714
CNT_DRAWINGS_ATM_CURRENT                      986559           17.627714
CNT_DRAWINGS_POS_CURRENT                      986559           17.627714
CNT_DRAWINGS_OTHER_CURRENT                    986559           17.627714
AMT_DRAWINGS_OTHER_CURRENT                    986559           17.627714
AMT_DRAWINGS_POS_CURRENT                      986559           17.627714
AMT_CREDIT_SUM_DEBT                           878452           15.696072
CNT_INSTALMENT_MATURE_CUM                     467831            8.359146
AMT_INST_MIN_REGULARITY                       467831            8.359146
DAYS_CREDIT_ENDDATE                           354614            6.336199
EXT_SOURCE_3                                  135698            2.424635
NAME_TYPE_SUITE                                 8438            0.150769
OBS_60_CNT_SOCIAL_CIRCLE                        2669            0.047689
OBS_30_CNT_SOCIAL_CIRCLE                        2669            0.047689
DEF_30_CNT_SOCIAL_CIRCLE                        2669            0.047689
DEF_60_CNT_SOCIAL_CIRCLE                        2669            0.047689
EXT_SOURCE_2                                    1615            0.028857
AMT_GOODS_PRICE                                  352            0.006289
AMT_ANNUITY_x                                    231            0.004127

In [10]:
numerical_columns_df = df_reduced.select_dtypes(include=['float64']).columns
df_reduced[numerical_columns_df] = df_reduced[numerical_columns_df].fillna(0.0)

In [11]:
categorical_columns_df = df_reduced.select_dtypes(include=['object']).columns
df_reduced[categorical_columns_df] = df_reduced[categorical_columns_df].fillna('Unknown')

Imputation of missing values of columns that contain 0/1 is tricky as it may bays the model and not towards the fact that the value was missing, but towards the fact the the value is particular.

Solution to this may be for each int64 that that was missing, when filling it with zero it may be beneficial to add aditional feature that would state <>name<>_was_mising and flag it as 1, otherwise 0. However, due to the wast dataset I was unable to do that this time, as kernel kept restarting.

In beter perfomance environment this code may be used to achieve the flagging:
for col in df.select_dtypes(include=['int64']).columns:
    df[col + '_was_missing'] = df[col].isnull().astype(int)
    df[col] = df[col].fillna(0)

In [12]:
new_columns = {}

for col in df_reduced.select_dtypes(include=['int64']).columns:
    new_columns[col + '_was_missing'] = df_reduced[col].isnull().astype(int)

missing_indicators_df = pd.DataFrame(new_columns)

df_reduced = pd.concat([df_reduced, missing_indicators_df], axis=1)

df_reduced.fillna({col: 0 for col in df_reduced.select_dtypes(include=['int64']).columns}, inplace=True)

In [13]:
numerical_columns_df = df_reduced.select_dtypes(include=['int64']).columns
df_reduced[numerical_columns_df] = df_reduced[numerical_columns_df].fillna(0)

In [14]:
pd.set_option("display.max_rows", None)

df = df_reduced

num_of_rows = len(df)
missing_values = df.isnull().sum()
missing_percentage = (missing_values / num_of_rows) * 100

missing_percentage_df = pd.DataFrame(
    {
        "Missing values (count)": missing_values,
        "Missing values (%)": missing_percentage,
    }
).sort_values("Missing values (%)", ascending=False)

missing_percentage_df = missing_percentage_df[
    missing_percentage_df["Missing values (%)"] > 0
]

missing_percentage_df

Empty DataFrame
Columns: [Missing values (count), Missing values (%)]
Index: []

In [15]:
df.to_csv("df_for_Neural_net.csv", index=False)

# Result

Extended dataset was created for Model 2 training.